Testing
YunoHost-Apps/searx_ynh pull request #91
Opened 2021-06-26 19:11 UTC by ericgaspar

- Keep config file

2021-06-26 19:11 UTC, ericgaspar commented
!testme

2021-07-20 18:06 UTC, yalh76 requested changes

2021-07-20 18:06 UTC, yalh76 commented on scripts/install
> +ynh_add_config --template="../conf/settings.yml" --destination="$final_path/searx/settings.yml" 2>/dev/null
why `2>/dev/null` is necessary ?

2021-07-20 18:06 UTC, yalh76 commented on scripts/install
> +ynh_add_uwsgi_service 2>/dev/null
why `2>/dev/null` is necessary ?

2021-07-20 19:00 UTC, ericgaspar commented
!testme

2021-07-20 20:03 UTC, yalh76 approved these changes

2021-08-04 17:49 UTC, merged